version: '3.7'
services:
  jupyterlab:
    build: .
    image: syunyooo/jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./work:/root/user/work:cached
    working_dir: /root/user/work
    command: sh /run.sh
    restart: always
    env_file:
      - .env
