version: '2.2'
services:
  jupyter:
    image: jupyter/datascience-notebook
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 8888:8888
    volumes:
      - ./jupyterlab:/home/jovyan/work
    working_dir: ./jupyterlab
    command: start-notebook.sh --NotebookApp.token=''
    restart: always