version: '3.7'
services:
  jupyterlab-nlp-ja:
    build: .
    image: syunyooo/jupyterlab-nlp-ja
    container_name: jupyterlab-nlp-ja
    ports:
      - 8888:8888
    volumes:
      - ./work:/root/user/work:cached
    working_dir: /root/user/work
    command: bash -c "sh /parser-test.sh && sh /run.sh"
    restart: always
