version: '3.7'
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./work:/root/user/work
    working_dir: /root/user/work
    command: sh /run.sh
    restart: always
  tensorboard:
    build: tensorboard
    volumes:
      - ./work/logs:/logs
    working_dir: /logs
    ports:
      - 6006:6006
    environment:
      reload_interval: 2
      log_dir: /logs
    restart: always